# Generated by Django 3.2.7 on 2021-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('reserve_check_in', models.DateTimeField()),
                ('reserve_check_out', models.DateTimeField()),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('reserved', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('room_number', 'reserve_check_in'), name='room reserved at specific time'),
        ),
    ]
