# Generated by Django 3.2.7 on 2021-09-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('bed_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('room_number',)},
            },
        ),
    ]
