# Generated by Django 3.2.7 on 2021-09-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0003_auto_20210906_1938'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='room reserved at specific time',
        ),
    ]
